### ISSUE TITLE
Installer fails with platform extensions

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-composer#22]
The installer will throw an exception when trying to install platform-xyz extensions into platform along with the default dependencies on a first `composer install` during installation of custom projects. This happens because the dependencies required to bootstrap the application (such as phptdotenv) are missing. We need to make sure that:
- the required dependencies are installed _first_
- the autoloader is present before we bootstrap the application

Originally reported at joomlatools/joomlatools-platform#240

Todo's:
- [x] Install/update after autoload is generated
- [x] Check if installed before queuing
- [x] Separate queue from ExtensionInstaller class
- [x] Fix uninstall?

**Comment by stevenrombauts** [comment]
@raeldc If you have 2 minutes to spare, could you test this? I've created a gist that sets everything up for you, all you need to do is verify that the installation works on your Joomlatools Box:

The following sets up Joomlatools Platform develop, adds extra components to composer.json and then installs it all in one go. Run this command:

curl -s https://gist.githubusercontent.com/stevenrombauts/fefee1e50135d0c766fd/raw/87b57c842ca826b232f7d660da116e90bf74c0b0/test-composer.sh | bash

Login at http://joomla.box/composertest/web/administrator and check if com_content, com_media and com_finder have been installed (and works)

Thanks!

**Comment by raeldc** [comment]
@stevenrombauts,

I'm having this error when running the script.

![screen shot 2016-03-07 at 4 35 39 pm](https://cloud.githubusercontent.com/assets/66454/13564180/a97fd800-e482-11e5-9e2a-a87322a1e72d.png)

**Comment by stevenrombauts** [comment]
Thanks @raeldc for testing! Looks like this constant has only recently been added to Composer in [49d7d659](https://github.com/composer/composer/commit/49d7d65933c78e163354c2c580883926f1c8daee). Not many people will have such a recent version so I went back to relying on the Symfony Console constants.

Could you give that test command above another run please?

**Comment by raeldc** [comment]
@stevenrombauts, it's working perfectly now. Awesome!

**Comment by johanjanssens** [comment]
@stevenrombauts @raeldc This issue is still marked as test. Did we release this? If so where, if not where should this go?

**Comment by stevenrombauts** [comment]
@johanjanssens We still need to release this. This should be working but to make it work properly in platform we also need to fix #23. But this should be mergeable.

**Comment by johanjanssens** [comment]
@stevenrombauts Can you check with @ercanozkaya This code was committed in develop and it seems it has been released with 1.1.0. Trying to clean this up a bit so the state of the repo reflects the work done, or things will get blurry after a while.

**Comment by ercanozkaya** [comment]
This was released as part of v1.1.0
