### ISSUE TITLE
Fire upgrade if extension is already registered

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-composer#23]
Consider the following scenario:
- Website is being deployed using a tool such as Capistrano
- The database already has the extension schema applied and is registered in assets/extensions tables
- A new deployment triggers composer install, which will try to re-install those extensions
- Errors will be thrown because the extension schema is already applied

To solve this : 
- After downloading of the files by Composer, check if the extension is already installed yes or no by looking at the database
- If not installed, run `install()`, otherwise run `update()`

**Comment by stevenrombauts** [comment]
The JInstallerAdapterComponent::update() method fails when trying to update if the extensions' code is missing because it tries to look for the old manifest. See: https://github.com/joomlatools/joomlatools-platform/blob/master/lib/libraries/cms/installer/adapter/component.php#L632-L650

This needs to be fixed in platform first.

**Comment by johanjanssens** [comment]
@stevenrombauts You need any help on this in the platform ?
