### ISSUE TITLE
Where to create the file composer.json

### ISSUE THREAD

**Issue by astridx** [joomlatools/joomlatools-composer#45]
I was about to try this repo. 
At the beginning of `Read.me` it says that you should create a `composer.json` in the `root directory` of `Joomla`. 

In the current Joomla version 3.9.14 there is already a `composer.json` in the `root directory`.

**Comment by stevenrombauts** [comment]
Hi @astridx! The instructions explain how to declare your custom package in your existing composer.json file. You only need to create a new one if there isn't one yet.  I'll rephrase the second line for clarity.

**Comment by astridx** [comment]
Thank you for the very quick feedback.

**Comment by johanjanssens** [comment]
Hello @astridx, 

Thanks for testing our composer installer. Looking at your site it seems you build some nice extensions for Joomla. At Joomlatools I have been working in the past 2 years on a new developer tool, called Joomlatools Pages, you can find more info here: https://github.com/joomlatools/joomlatools-pages/wiki

Joomlatools Pages is an easy to use dynamic page generator for Joomla inspired by the ideas and concepts of flat-file CMS systems like Grav and Statamic and static site generators like Jekyll, Hugo, Gatsby etc.

We used it to re-build our Joomlatools.com site last year and I continue to work on it. Pages offers a lot of cool feature that I think you will enjoy. Your feedback would be most appreciated. You can easily get in touch with us at https://gitter.im/joomlatools/dev
